// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzqxzrgjuidtvzilckul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6cXh6cmdqdWlkdHZ6aWxja3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODQwNTYsImV4cCI6MjA2MjQ2MDA1Nn0.Z2Y_l-U7xx-RkoEZosOAPRrQZLEBERYeVTmUpIOAqnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);